steps:
  # Step 1: Install dependencies on the build agent - to validate requirements.txt is valid
  - name: 'python:3.10.5' # This defines the Docker image/environment where the command will run.
    id: 'validate-requirements' # This provides a unique identifier for this build step.
    entrypoint: pip # This specifies the executable that will run instead of the default entry point of the container.
    args: ['install', '-r', 'requirements.txt', '--user'] # These are the arguments passed to the command specified in "entrypoint".

  # Step 2: Run unit tests on the build agent
  - name: 'python:3.10.5'
    id: 'run-unit-tests'
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install unittest-xml-reporting --user
        python -m xmlrunner discover -s . -p "*_tests.py" -o /workspace/test-reports

  # Step 3: Build the function package
  - name: 'gcr.io/cloud-builders/docker'
    id: 'containerize-application'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '.'

  # Step 4: Upload app container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-container-image'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${SHORT_SHA}']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-function-to-cloud-run'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${SHORT_SHA}', '--region', '${_REGION}']

# Define the artifacts to keep
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/'
    paths: 
      - 'test-reports/**/*.xml'

# Substitution variables
substitutions:
  _SERVICE_NAME: 'my-mathematics-function'     # Name of service
  _IMAGE_NAME: 'my_mathematics_function_image' # Image name prefix
  _REGION: 'us-south1'                         # Your preferred region
  _ARTIFACT_BUCKET: 'my_mathematics_function_bucket'  # GCS bucket for other artifacts
  _ARTIFACT_REGISTRY_REPO: 'my-mathematics-function-repo' # Artifact Registry repo for image artifacts

# Timeout for the entire build process
timeout: '1800s'  # 30 minutes